{
  imports = [
    ./auto_shutdown.nix
    ./boot.nix
    ./cachix.nix
    ./crypto.nix
    ./docker.nix
    ./lib.nix
    ./maintenance.nix
    ./network.nix
    ./nfs.nix
    ./nomad.nix
    ./packages.nix
    ./panic_button.nix
    ./prometheus.nix
    ./live_system.nix
    ./load_json.nix
    ./reverse-tunnel.nix
    ./sshd.nix
    ./system.nix
    ./syno_vm.nix
    ./traefik.nix
    ./users.nix
    ./vim-config.nix
    ./virtualbox.nix
    ./vmware.nix
  ];
}

