
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    cryptsetup
    keyutils
    wget
    curl
    (import ./vim-config.nix)
    coreutils
    gptfdisk
    file
    nfsUtils
    cifs-utils
    htop
    iotop
    lsof
    psmisc
    rsync
    git
    acl
    mkpasswd
    unzip
    lm_sensors
    ipset
    nmap
    traceroute
    ethtool
    tcptrack
    bind
    dmidecode
    p7zip
    nix-info
    nix-bundle
    # We need python3 to be able to control the machine using Ansible
    python3
  ];

}

