
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    git
    docker_compose
  ]; 

  boot.kernel.sysctl = {
    "vm.overcommit_memory" = 1;
    "net.core.somaxconn" = 65535;
  };

  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
    extraOptions = "--data-root=/opt/docker";
  };

  systemd.services.docker = {
    wants = [ "network-online.target" ];
    after = [ "network-online.target" ];
  };

}

