
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    git
    docker_compose
  ]; 

  boot.kernel.sysctl = {
    "vm.overcommit_memory" = 1;
    "net.core.somaxconn" = 65535;
  };

  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
    # Do not break currently running non-encrypted set-ups.
    extraOptions = lib.mkIf config.settings.crypto.enable "--data-root=/opt/docker";
  };
  
  environment.etc.docker_conf = {
    enable = true;
    target = "docker/daemon.json";
    text = ''
      {
        "bip": "10.231.0.1/24",
        "default-address-pools": [
          {
            "scope": "local",
            "base": "10.232.0.0/16",
            "size": 24
          },
          {
            "scope": "global",
            "base": "10.233.0.0/16",
            "size": 24
          }
        ]
      }
    '';
  };

  systemd.services.docker = {
    wants = [ "network-online.target" ];
    after = [ "network-online.target" ];
  };

}

