
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, ... }:

{
# Enable cron service
  services.cron = {
    enable = true;
    systemCronJobs = [
      "5 4 * * * root date >>/root/kobohack.log;cd /opt/kobo-docker/;docker-compose exec kpi bash -c 'rm /tmp/celery*';docker-compose restart >> /root/kobohack.log"
    ];
  };

}

