
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

with lib;

{
  options = {
    settings.kobofix.kobo_directory = mkOption {
      default = "/opt/kobo-docker";
      type = types.str;
    };
  };

  config = {
    systemd.services.kobofix = {
      enable = true;
      serviceConfig = {
        User = "root";
        Type = "oneshot";
        WorkingDirectory = config.settings.kobofix.kobo_directory;
      };
      path = [ pkgs.docker ];
      restartIfChanged = false;
      script = ''
        echo "Running rm /tmp/celery* ..."
        ${pkgs.docker_compose}/bin/docker-compose exec -T kpi sh -c 'rm /tmp/celery*'
        echo "Restarting the containers ..."
        ${pkgs.docker_compose}/bin/docker-compose restart
      '';
      startAt = "04:05";
    };
  };
}

