
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib, config, pkgs, ... }:

{

  system.autoUpgrade = {
    enable = true;
    dates = "Mon 03:20";
  };

  systemd = {
    services = {
      nixos-upgrade = {
        serviceConfig = {
          TimeOutStartSec = "2 days";
        };
        script = let
          cfg = config.system.autoUpgrade;
          nixos-rebuild = "${config.system.build.nixos-rebuild}/bin/nixos-rebuild";
          date = "/run/current-system/sw/bin/date";
          readlink = "/run/current-system/sw/bin/readlink";
          shutdown = "/run/current-system/sw/bin/shutdown";
        in lib.mkForce ''
          ${nixos-rebuild} boot --no-build-output --upgrade
          booted="$(${readlink} /run/booted-system/{initrd,kernel,kernel-modules})"
          built="$(${readlink} /nix/var/nix/profiles/system/{initrd,kernel,kernel-modules})"
          threshold="$(${date} --date="$(${date} --date='today' +%Y-%m-%d) 05:00" +%s)";

          if [ "$booted" = "$built" ]; then
            ${nixos-rebuild} switch --no-build-output
          elif [ "$(${date} +%s)" -gt "''${threshold}" ]; then
            echo "Reboot max time exceeded, skipping."
          else
            ${shutdown} -r +1
          fi
        '';
      };
    };
    # Run the upgrade service during the day, to catch the situation where servers
    # are turned off every evening. We will be outside of the reboot window.
    timers = {
      nixos-upgrade-day = {
        timerConfig = {
          Unit = "nixos-upgrade.service";
          OnCalendar = "Mon 12:00";
        };
        wantedBy = [ "timers.target" ];
      };
    };
  };

  nix = {
    autoOptimiseStore = true;
    gc = {
      automatic = true;
      dates = "Tue 03:00";
      options = "--delete-older-than 30d";
    };
  };

}

