
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib }:

# Usage:
#   with (import ../msf_lib.nix { inherit lib; });
#   msf_lib.<identifier>

with lib;

{

  msf_lib = {
    # A type for host names, host names consist of:
    #   * a first character which is an upper or lower case ascii character
    #   * followed by zero or more of: dash (-), upper case ascii, lower case ascii, digit
    #   * followed by an upper or lower case ascii character or a digit
    host_name_type =
      types.strMatching "^[[:upper:][:lower:]][-[:upper:][:lower:][:digit:]]*[[:upper:][:lower:][:digit:]]$";
  };

}

