
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib }:

# Usage:
#   with (import ../msf_lib.nix { inherit lib; });
#   msf_lib.<identifier>

with lib;

{
  msf_lib = {
    # A type for host names, host names consist of:
    #   * a first character which is an upper or lower case ascii character
    #   * followed by zero or more of: dash (-), upper case ascii, lower case ascii, digit
    #   * followed by an upper or lower case ascii character or a digit
    host_name_type =
      types.strMatching "^[[:upper:][:lower:]][-[:upper:][:lower:][:digit:]]*[[:upper:][:lower:][:digit:]]$";

    importIfExists = path: optional (builtins.pathExists path) path;

    user_roles = rec {
      # Admin users have shell access, belong to the wheel group, and are enabled by default
      admin = {
        enable      = true;
        sshAllowed  = true;
        hasShell    = true;
        canTunnel   = true;
        extraGroups = [ "wheel" "docker" ];
      };
      # Users who can tunnel only
      # These are not enabled by default and should be enabled on a by-server basis
      tunnelOnly = {
        enable     = mkDefault false;
        sshAllowed = true;
        hasShell   = false;
        canTunnel  = true;
      };
      # Users who are tunnel-only but can tunnel to all NixOS servers
      tunnelOnlyAllServers = tunnelOnly // { enable = true; };
    };
  };
}

