
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  imports = [
    ./users/tunnel.nix
    ./users/tunneller.nix
  ];

  users.extraUsers.tunnel.openssh.authorizedKeys.keyFiles = [ ../keys/tunnel ];

  services.openssh = {
    ports = [ 22 80 443 ];
  };

}

