
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, ... }:

let
  reverse_tunnel = config.settings.reverse_tunnel;
in

with lib;

{

  config.services.openssh = {
    enable = true;
    permitRootLogin = "no";
    forwardX11 = false;
    passwordAuthentication = false;
    challengeResponseAuthentication = false;
    ports = mkIf reverse_tunnel.relay.enable reverse_tunnel.relay.ports;
    extraConfig = ''
      StrictModes yes
      AllowAgentForwarding no
      TCPKeepAlive yes
      ClientAliveInterval 60
      ClientAliveCountMax 3
      UseDNS no
      GSSAPIAuthentication no
      KerberosAuthentication no

      AllowTcpForwarding no

      Match Group wheel
        AllowTcpForwarding yes

      ${optionalString reverse_tunnel.relay.enable ''
        Match User tunnel
          AllowTcpForwarding remote

        Match User tunneller
          # Required to be able to proxy through the relay
          AllowTcpForwarding local
      ''}
    '';
  };

}

