
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

let
  reverse_tunnel = config.settings.reverse_tunnel;
in

with lib;

{

  config = {

    environment.systemPackages = with pkgs; [
      ipset
    ];

    services = {
      openssh = {
        enable = true;
        authorizedKeysFiles = mkForce [ "/etc/ssh/authorized_keys.d/%u" ];
        permitRootLogin = "no";
        forwardX11 = false;
        passwordAuthentication = false;
        challengeResponseAuthentication = false;
        allowSFTP = mkIf reverse_tunnel.relay.enable false;
        ports = mkIf reverse_tunnel.relay.enable reverse_tunnel.relay.ports;
        extraConfig = ''
          StrictModes yes
          AllowAgentForwarding no
          TCPKeepAlive yes
          ClientAliveInterval 10
          ClientAliveCountMax 5
          GSSAPIAuthentication no
          KerberosAuthentication no

          AllowGroups wheel ${config.settings.users.ssh-group}

          AllowTcpForwarding no

          Match Group wheel
            AllowTcpForwarding yes

          Match Group ${config.settings.users.fwd-tunnel-group},!wheel
            AllowTcpForwarding local

          ${optionalString reverse_tunnel.relay.enable ''
            Match User tunnel
              AllowTcpForwarding remote

            Match User tunneller
              # Required to be able to proxy through the relay
              AllowTcpForwarding local
          ''}
        '';
      };

      sshguard = {
        # Error in logs, "could not initialize firewall"
        enable = false;
        blocktime = 600;
        # 7 * 24 * 60 * 60
        detection_time = 604800;
      };
    };
  };

}

