
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  boot.loader = {
    grub = {
      enable = true;
      # Use the GRUB 2 boot loader.
      version = 2;
      efiSupport = true;
      efiInstallAsRemovable = true;
      # boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only
      device = "nodev";
      memtest86.enable = true;
    };
    efi.efiSysMountPoint = "/boot/efi";
  };

}

